# -*- coding: utf-8 -*-
"""Copy of Prompting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fl_5Gr8pB6syTT3VivUzMiKKXgoltIBK

# Gemini API: Prompting Quickstart
"""
import reflex as rx

# !pip install -U -q google.generativeai # Install the Python SDK

import google.generativeai as genai

"""## Set up API key"""

"""## Set parameters

"""

"""## Run script

"""

# response = model.generate_content(
# text_scribe
# # ,
#     # Limit to 5 facts.
#     #generation_config = genai.GenerationConfig(stop_sequences=['\n6'])
# )
# print(response.text)
# class scribeState(rx.State):
    
def scribeGenerator(text_scribe):
        GOOGLE_API_KEY="AIzaSyAM2QVm-CFBibfLtq7H-Ed3yL6gi9qNA7A"
        genai.configure(api_key=GOOGLE_API_KEY)
        model = genai.GenerativeModel(
            "models/gemini-1.5-pro-latest",
            generation_config=genai.GenerationConfig(
                temperature=0.5,
            ),
            system_instruction="You're a professional doctor supervisor with 10 years plus expereince supervising a new medical doctor, based on the dialog script I provided you, understand if the doctor in the script makes any mistakes, their potencial area of improvement and give some suggestions to the doctor being quality checked on. Do not include the positive parts. ",
        )
        print("calling scribeGenerator")
        print(model.generate_content(text_scribe))
